<?php
// @see: https://kb.newsman.ro/api/1.2/template.mailTemplateAdd
// you can get your API KEY and your newsman_user_id from My account -> API
require_once("Newsman/Client.php");

try
{
	$client = new Newsman_Client($newsman_user_id, $api_key);
	$ret = $client->template->mailTemplateAdd(
		$list_id, /* The list id for this mail template. */
		$type, /* The template type. Can be any of: unsubscribe_confirm - for unsubscribe mail confirmation content subscribe_confirm - for subscribe mail confirmation content */
		$subject, /* - The subject for the mail sent out. */
		$text, /* - The TEXT body of email sent out. If null it will be autogenerated from the HTML content. */
		$html /* - The HTML body of the email sent out. */
	);
} catch (Exception $e)
{
	//handle exception here
}
?>